### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ac0rdj** [nigel/DiscordStorage#6]
There is an error after following all instructions: 
![unknown-3](https://user-images.githubusercontent.com/71348309/109531179-942abd00-7a85-11eb-928a-b504f168e3a4.png)

**Comment by ac0rdj** [comment]
fixed this but now its saying
Traceback (most recent call last):
  File "/Users/-/DiscordStorage/ds.py", line 1, in <module>
    from discordstorage import core
  File "/Users/-/DiscordStorage/discordstorage/core.py", line 1, in <module>
    import os,io,aiohttp,asyncio, discord
ModuleNotFoundError: No module named 'discord'

**Comment by ac0rdj** [comment]
Please put in the instructions to install all these modules. Thanks! works awesome!
